[tool.poetry]
name = "anomaly"
version = "0.1.0"
description = ""
authors = ["Marianikolaevnav <marianikv1998@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
numpy = "^1.24.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
